data:
  unlabel_dir: data/Dataset_Student/unlabeled
  batch_size: 32
  patch_size: 16
  pin_mem: True
  num_workers: 4
  drop_last: True
  num_clips: 1

  collate:
    crop_size: [160, 240]
    num_frames: 11
    tubelet_size: 2

optimizer:
  ipe: 300
  ipe_scale: 1.25
  clip_grad: 10.0
  weight_decay: 0.04
  final_weight_decay: 0.4
  num_epochs: 25
  warmup: 40
  start_lr: 0.0002
  lr: 0.000625
  final_lr: 1.0e-06
  ema:
  - 0.998
  - 1.0

meta:
  load_checkpoint: false
  read_checkpoint: null
  seed: 234
  eval_freq: 100
  use_sdpa: true
  dtype: bfloat16

mask:
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 8
    spatial_scale:
      - 0.15
      - 0.15
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 2
    spatial_scale:
      - 0.7
      - 0.7
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null